### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by austinkregel** [Superbalist/laravel-google-cloud-storage#1]
Hello, I tried installing your package, however installation failed and I received the following message. I am using a fresh installation of Laravel 5.3. If any more information is needed/wanted about this, please let me know. :)

```
Using version ^1.0 for superbalist/laravel-google-cloud-storage
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for superbalist/laravel-google-cloud-storage ^1.0 -> satisfiable by superbalist/laravel-google-cloud-storage[1.0.0].
    - superbalist/laravel-google-cloud-storage 1.0.0 requires superbalist/flysystem-google-storage ^3.0 -> satisfiable by superbalist/flysystem-google-storage[3.0.0, 3.0.1, 3.0.2, 3.0.3].
    - superbalist/flysystem-google-storage 3.0.0 requires google/cloud ^0.8.0 -> satisfiable by google/cloud[v0.8.0].
    - superbalist/flysystem-google-storage 3.0.1 requires google/cloud ^0.8.0 -> satisfiable by google/cloud[v0.8.0].
    - superbalist/flysystem-google-storage 3.0.2 requires google/cloud ^0.8.0|^0.9.0 -> satisfiable by google/cloud[v0.8.0, v0.9.0].
    - superbalist/flysystem-google-storage 3.0.3 requires google/cloud ^0.8.0|^0.9.0 -> satisfiable by google/cloud[v0.8.0, v0.9.0].
    - google/cloud v0.8.0 requires google/auth 0.10 -> satisfiable by google/auth[v0.10].
    - google/cloud v0.9.0 requires google/auth 0.10 -> satisfiable by google/auth[v0.10].
    - Conclusion: don't install google/auth v0.10

```

**Comment by thebrubaker** [comment]
Had the same problem, forgot to composer remove websight/l5-google-cloud-storage

Not sure if you were using websight's package before, but it fixed the issue above for me.

**Comment by thebrubaker** [comment]
I think I also had to add composer require superbalist/flysystem-google-storage as well.

**Comment by markhilton** [comment]
Laravel 5.2

composer require superbalist/laravel-google-cloud-storage                                                                                                           ‹system›
Using version ^1.0 for superbalist/laravel-google-cloud-storage
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for superbalist/laravel-google-cloud-storage ^1.0 -> satisfiable by superbalist/laravel-google-cloud-storage[1.0.0].
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - superbalist/laravel-google-cloud-storage 1.0.0 requires illuminate/filesystem ^5.3 -> satisfiable by illuminate/filesystem[v5.3.0, v5.3.16, v5.3.4].
    - don't install illuminate/filesystem v5.3.0|don't install laravel/framework v5.2.45
    - don't install illuminate/filesystem v5.3.16|don't install laravel/framework v5.2.45
    - don't install illuminate/filesystem v5.3.4|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].

Installation failed, reverting ./composer.json to its original content.

**Comment by matthewgoslett** [comment]
@markhilton 
It looks like you're using Laravel 5.2, but we when we developed this, we built it for 5.3 (or at least made 5.3 a dependency).
Any chance you can branch off and test compatibility with 5.2?
If so, we can lower the requirement here.

**Comment by matthewgoslett** [comment]
@austinkregel 
Can you give me the output of the following (when inside your project directory)
`composer depends google/cloud`
`composer depends google/auth`

**Comment by austinkregel** [comment]
@matthewgoslett  Sorry I didn't respond earlier, it seems like what @thebrubaker had the right idea. I thought I didn't have that package installed, but I guess I did. Which is what was causing my issues.

**Comment by matthewgoslett** [comment]
No problem.
Ye that would cause a dependency conflict.
`websight/l5-google-cloud-storage` no longer uses `flysystem-google-cloud-storage` which this packages uses under the hood.  It looks like they tie themselves to a specific version of `google/cloud`.

**Comment by tristan5293** [comment]
Laravel 5.2.43
![laravel_5 2](https://cloud.githubusercontent.com/assets/12492048/19721046/36c29a2c-9ba3-11e6-9ca9-6e91c0a726af.png)

can you support laravel 5.2 ? laravel 5.3 is too fresh

**Comment by austinkregel** [comment]
I'm going to close this issue as my problems were resolved. @tristan5293 can you please make your own issue to continue the discussion there. Thanks :)
