### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by lehnen** [Superbalist/laravel-google-cloud-storage#100]
Hi,
will the package get available for Laravel 8.x. ?

Greetings from Germany
Volker

**Comment by sdwru** [comment]
+1

**Comment by hunkok** [comment]
+1

**Comment by shahvirag** [comment]
+1

**Comment by mous2890** [comment]
https://github.com/Superbalist/laravel-google-cloud-storage/pull/99 

PR raised.

**Comment by spacedog4** [comment]
+1

**Comment by nikolaos-spyratos** [comment]
Laravel 8 version as of 2.2.4 :)
