### ISSUE TITLE
Support: How to let user download files from the GCS bucket?

### ISSUE THREAD

**Issue by akulmehta** [Superbalist/laravel-google-cloud-storage#101]
Sorry for my naivety in advance. I am able to upload files into GCS using this plugin (which is great), but how do I let users of my Laravel application download files? Do I make a custom route to download a file and what would the route contain, an example would be nice to add in the documentation.

**Comment by akulmehta** [comment]
I figured it out and here is the code for anyone who may need it in the future.

I created a route and controller `FileController` to handle downloads as I did not want to expose the path in my Cloud Storage. This also allowed to control users based on middleware e.g. logged in users allowed only. This is the download function in the FileController.

```
    public function download($pathToFile) {
        $disk = \Storage::disk('gcs');
        return $disk->download($pathToFile);
    }
```

In my web.php the following line:

```
Route::get('/download/{pathToFile}', 'FileController@download')->name('file.download');
```

**Comment by rimaregiani** [comment]
thanks!
