### ISSUE TITLE
Move a file that exists locally to google cloud

### ISSUE THREAD

**Issue by aghwotu** [Superbalist/laravel-google-cloud-storage#110]
Hello there. Thank you for this package. I want to upload a pdf file I already stored locally to Google Cloud Storage. Please how do I do this? Thank you for your time. 

```php
$data = [
    'title' => 'This is my title',
    'date' => date('m/d/Y')
];
$filename = "JohnDoe";
$filename .= ".pdf";
$pdf = PDF::loadView('myPDF', $data); 
$fileStoragePath = '/path/to/pdf/' . $filename;
$path = public_path($fileStoragePath);
$pdf->save($path);

$disk = Storage::disk('gcs');
// create a file - store pdf in the cloud
$disk->put('pdf/1.txt', 'Contents of sample text file');
```

**Comment by idealerror** [comment]
I believe you already had the answer at the end of your code.

```php
$disk = Storage::disk('gcs');
// create a file - store pdf in the cloud
$disk->put('your.pdf', file_get_contents($path));
```

**Comment by aghwotu** [comment]
Hello, 👋 there. Thank you for your kind response. 
I have long since deployed this project and forgot to close the issue. I also wrote a tutorial about it [here ](https://dev.to/ediri_aghwotu/how-to-upload-files-to-google-cloud-using-laravel-3618)

Thank you again.

**Comment by idealerror** [comment]
Great writeup! :)
