### ISSUE TITLE
GoogleException in ClientTrait.php line 114: Given keyfile path does not exist on heroku

### ISSUE THREAD

**Issue by wapnen** [Superbalist/laravel-google-cloud-storage#12]
everything works fine on my local server however when i deploy to heroku i get the following error "GoogleException in ClientTrait.php line 114:
Given keyfile path does not exist"

i do not want to add my key file to git for security reasons. how else do i upload the key file to heroku and set the path ?

**Comment by wapnen** [comment]
UPDATE: ive found a way to set the key file as a config variable in heroku, however the contents exceed the character limit of 255. any way to change the limit?

**Comment by matthewgoslett** [comment]
I can't really advise on how this should work with Heroku.

As a general principle, have the key (or secret) deployed to the server or container.
Set the `GOOGLE_APPLICATION_CREDENTIALS` env var to the path of that key file.

**Comment by rslhdyt** [comment]
this problem happened to me, when applications run in continous integrations for build and testing purpose. I get same error exceptions like @wapnen 

"GoogleException in ClientTrait.php line 114: Given keyfile path does not exist"

**Comment by rensphilipsen** [comment]
Same problem as @sogeniusio. Any solution?

**Comment by rensphilipsen** [comment]
As I am using Laravel Homestead with Vagrant, I had to put the .json within the VM of Laravel Homestead.

So make sure you have this json on your VM instead of your local machine and specify the path to the file based on your VM (in my case: /home/vagrant/service-account.json)
