### ISSUE TITLE
Caller does not have access

### ISSUE THREAD

**Issue by RaiserWeb** [Superbalist/laravel-google-cloud-storage#14]
I am getting the following response error - it appears I have given correct role access to the API client in google

{
"error": {
"errors": [
{
"domain": "global",
"reason": "forbidden",
"message": "Caller does not have storage.objects.get access to object your-bucket/test.txt."
}

**Comment by matthewgoslett** [comment]
This sounds like a ACL / permissions issue.

If you google "Caller does not have storage.objects.get access to ", you'll find some similar issues.
