### ISSUE TITLE
Can't Delete Directory Laravel 5.4

### ISSUE THREAD

**Issue by loooping** [Superbalist/laravel-google-cloud-storage#16]
I try delete a sub-directory of my Google Cloud Storage, but give me a error.

```
$disk = Storage::disk('gcs');
$dir = 'directory/2/otherdir/3'; <- i need delete this directory

$disk->deleteDirectory($dir);
```

I HAVE THIS RETURN

```
[19:35:45] LOG.error: Google\Cloud\Core\Exception\NotFoundException: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "Not Found"
   }
  ],
  "code": 404,
  "message": "Not Found"
 }
}
 in /Users/pablo/Sistemas/clientsystem/vendor/google/cloud/src/Core/RequestWrapper.php:241
```

**Comment by BradWhittington** [comment]
GCS doesn't have a concept of directories, you have to iterate and remove each object - https://stackoverflow.com/questions/5630093/how-to-delete-folder-with-files-using-google-storage-rest-api

**Comment by loooping** [comment]
Yeah I know, but
I'm have to use method ->delete() or do task manually out of the your package?
