### ISSUE TITLE
Dynamic driver instance for different buckets

### ISSUE THREAD

**Issue by eodin** [Superbalist/laravel-google-cloud-storage#23]
I need to access different buckets dynamically depending on params
```php
$param = parse_url('gs://mybucket/path/to/file');
Config::set('filesystems.disks.gcs.bucket', $param['host']); // maybe works
$file = Storage::disk('gcs')->get($param['path']);
```
Or something like 
```php
$storage = Storage::createS3Driver([
    'driver' => 's3',
    'key'    => 'your-key',
    'secret' => 'your-secret',
    'region' => 'us-east-1',
    'bucket' => $bucketName,
]);
```

**Comment by zoidbergwill** [comment]
The only dynamic stuff we do is for different env vars in different environments using the following:

```
        'connections' => array(
                // ...
                'gcloud' => array(
                        'adapter' => 'gcloud',
                        'bucket' => env('STORAGE_GCLOUD_BUCKET'),
                ),
        ),
```

But if you need the dynamic buckets at runtime, I'd suggest you fork [flystem-google-cloud-storage](https://github.com/Superbalist/flysystem-google-cloud-storage) to support different buckets for [`write`](https://github.com/Superbalist/flysystem-google-cloud-storage/blob/dcce953d2324bb10a12f9448f5a552c166f8c257/src/GoogleStorageAdapter.php#L16:36)

Or you could just generate a `Google\Cloud\Storage\StorageClient`, and then dynamic buckets from that client the way we instantiate the bucket [here](https://github.com/Superbalist/laravel-google-cloud-storage/blob/master/src/GoogleCloudStorageServiceProvider.php#L24), doing something like:

```php
$storageClient = new StorageClient([
    'projectId' => $projectId,
    'keyFilePath' => $keyFile,
]);
$bucket = $storageClient->bucket($bucketName);
```
