### ISSUE TITLE
StyleCI: Error 404 Repo not found.

### ISSUE THREAD

**Issue by sinkcup** [Superbalist/laravel-google-cloud-storage#26]
maybe should remove StyleCI link in `README.md`

![image](https://user-images.githubusercontent.com/4971414/35894911-f63d12a2-0bef-11e8-9a93-74b614f12727.png)

![image](https://user-images.githubusercontent.com/4971414/35894930-0da5c27c-0bf0-11e8-8cb6-0b36bc95bb98.png)

**Comment by zoidbergwill** [comment]
Or we can enable Style CI on this repo :P
