### ISSUE TITLE
update to Superbalist/flysystem-google-cloud-storage 7.0

### ISSUE THREAD

**Issue by sinkcup** [Superbalist/laravel-google-cloud-storage#28]
Superbalist/flysystem-google-cloud-storage#74

**Comment by zoidbergwill** [comment]
Released https://github.com/Superbalist/laravel-google-cloud-storage/releases/tag/1.0.6

**Comment by sinkcup** [comment]
@zoidbergwill maybe use tag 1.1.0 or 2.0.0 is better, this is a big change, maybe couse some problem if using 1.0.6

**Comment by zoidbergwill** [comment]
Yeah, we've bumped major changes of dependencies before in minor version bumps, but it is probably a bad idea.

**Comment by zoidbergwill** [comment]
I've made [2.0.0](https://github.com/Superbalist/laravel-google-cloud-storage/releases) and deleted 1.0.6

**Comment by sinkcup** [comment]
great! I see you have delete 1.0.6 on packagist.org, maybe should remove tag in github too.

**Comment by sinkcup** [comment]
1.0.6 is always here: https://github.com/Superbalist/laravel-google-cloud-storage/tags

try this:

```
git tag -d 1.0.6
git push origin master
```

**Comment by zoidbergwill** [comment]
I've deleted the tag on GitHub
