### ISSUE TITLE
Signed URL support?

### ISSUE THREAD

**Issue by baj84** [Superbalist/laravel-google-cloud-storage#35]
Hi, Is there a way of generating a signed url?

Cheers

**Comment by asaslaw** [comment]
The functionality is already there. Superblast loads the google classes and thats all you need. At least, this works if you are on GCE. I haven't tried on anything else. 

$storageClient = new StorageClient([
    'projectId' => 'yourID',
    'keyFilePath' => '../config/keyfile.json',  //I put my keyfile in the config folder
]);
$bucket = $storageClient->bucket('yourbucketname');
$object = $bucket->object(YOURFILEINTHEBUCKET);
$url = $object->signedUrl(new \DateTime('tomorrow'));

**Comment by JensJI** [comment]
Can also be written like this:

```
$url = Storage::getAdapter()
            ->getBucket()
            ->object($filepath)
            ->signedUrl(now()->addMinutes(15));
```

**Comment by fgilio** [comment]
Thanks @JensJI
