### ISSUE TITLE
Driver is not Supported

### ISSUE THREAD

**Issue by asaslaw** [Superbalist/laravel-google-cloud-storage#36]
Greetings. I am attempting to install this on Laravel 5.5.24 and getting an error when I try to call

$disk = Storage::disk('gcs');

The error I am getting is "Driver[] is not supported"

UPDATE: Just had to do a publish:vendor, I forgot to do that.

**Comment by aCodeAlchemist** [comment]
@asaslaw how did you do "publish:vendor"? can you please provide me command?
