### ISSUE TITLE
It's Compatibility with lumen?

### ISSUE THREAD

**Issue by deyvsonaguiar** [Superbalist/laravel-google-cloud-storage#41]
Hello, 

This packet is compatible with lumen?

**Comment by nicja** [comment]
Hi @deyvsonaguiar  Did you try this with Lumen? Can you comment on your results?

**Comment by ashutoshpathak200** [comment]
I have this working with Lumen in production.

**Comment by nicja** [comment]
@ashutoshpathak200 great news, thank you! :+1:
