### ISSUE TITLE
Question: How could i perform a parallel (multi-threaded/multi-processing) copy?

### ISSUE THREAD

**Issue by Zanzavar** [Superbalist/laravel-google-cloud-storage#43]
New to Laravel and gcs here. I am performing a copy operation from a gcs directory to another gcs directory with a few images inside, however it takes around 8-10 secs for the process to complete:

```
 foreach` ($files as $file) {
     $targetFile = $target.substr($file, strpos($file, '/'));
     Storage::disk(self::Disk())->copy($file, $targetFile);
 `}
```

I know that  gsutil has the -m command to copy multiple files like so:

`gsutil -m cp -r dir gs://my-bucket
`
Is there a way i could do something similar(multi-process) in Laravel?

**Comment by cjcox17** [comment]
I don't think this is possible, PHP only supports multi-threading via the ZTS extension which requires you to manually compile PHP. I've tried it and haven't gotten it to work with Laravel.

As far as a google supported function in their library, their documentation states that you must call the method per object for the client libraries (see below).

Source: [https://cloud.google.com/storage/docs/renaming-copying-moving-objects#storage-rename-object-php](https://cloud.google.com/storage/docs/renaming-copying-moving-objects#storage-rename-object-php)
> Note: The gsutil command line tool supports copying multiple objects with a common prefix, however the REST APIs and the Cloud Storage client libraries only support copying individual objects. To copy multiple objects using the REST APIs or Cloud Storage client libraries, call the method once for each object.
