### ISSUE TITLE
does this package or google cloud storage has the ability to upload multiple files together or move multiple files together?

### ISSUE THREAD

**Issue by novaknole** [Superbalist/laravel-google-cloud-storage#47]
does this package or google cloud storage has the ability to upload multiple files together or move multiple files together? I was looking for the way, but couldn't find any.

**Comment by nicja** [comment]
As far as I can tell this is not possible 
[1] https://stackoverflow.com/a/39137150/685706
[2] https://cloud.google.com/storage/docs/
