### ISSUE TITLE
getClient() undefined.

### ISSUE THREAD

**Issue by esilvajr** [Superbalist/laravel-google-cloud-storage#49]
**Stack:**
PHP7.2
Laravel 5.5

**Error:**
Call to undefined method Superbalist\\Flysystem\\GoogleStorage\\GoogleStorageAdapter::getClient() at /application/app/Providers/FacadeServiceProvider.php:32

Install following the readme.md docs and when i'll use grab this error.

Using like:

\StorageClient::putObject("SOME INFO HERE");

'StorageClient'  is a facade \App\Facades\StorageClient::class

Could you help me plz?

regards,

**Comment by nicja** [comment]
The file that is causing the error (`/application/app/Providers/FacadeServiceProvider.php`) and the StorageClient clas are not part of this package, so I'm unable to help..

If you can share that code perhaps I can help point you in the right direction.
