### ISSUE TITLE
Call to undefined method Superbalist\LaravelGoogleCloudStorage\GoogleCloudStorageServiceProvider::createCacheStore()

### ISSUE THREAD

**Issue by ignaczistvan** [Superbalist/laravel-google-cloud-storage#50]
Stack:
PHP 7.1
Laravel 5.7
laravel-google-cloud-storage 2.1

If I add 'cache' config parameters the ServiceProvider fails: Call to undefined method Superbalist\LaravelGoogleCloudStorage\GoogleCloudStorageServiceProvider::createCacheStore() at GoogleCloudStorageServiceProvider.php:30

Did I miss something obvious or is it a bug?
Thanks!

**Comment by nicja** [comment]
This has been fixed in version https://github.com/Superbalist/laravel-google-cloud-storage/releases/tag/2.1.1

**Comment by ignaczistvan** [comment]
thanks!
