### ISSUE TITLE
Given keyfile path /*/ does not exist

### ISSUE THREAD

**Issue by victoralbino** [Superbalist/laravel-google-cloud-storage#62]
I include in my app.yaml file the variable:
`GOOGLE_CLOUD_KEY_FILE: "/home/nameuser/projectFile/key.json"`
equivalent to the path within App Engine, however the following error appears:

> Given keyfile path /home/nameuser/projectFile/key.json does not exist

I do not know if I did something wrong.

**Comment by Divala** [comment]
@victoralbino how did you resolve the issue? I have the same problem

**Comment by victoralbino** [comment]
@Divala 
To solve the problem I removed the GOOGLE_CLOUD_KEY_FILE variable from the app.yml file and added it to `config/filesystems.php`.

**Old .env:**
`FILESYSTEM_CLOUD: gcs`
`GOOGLE_CLOUD_PROJECT_ID: {project_id}`
`GOOGLE_CLOUD_STORAGE_BUCKET: {xxxxxxxxx}.appspot.com`
`GOOGLE_CLOUD_KEY_FILE: "/home/nameuser/projectFile/key.json"`

**New .env**
`FILESYSTEM_CLOUD: gcs`
`GOOGLE_CLOUD_PROJECT_ID: {project_id}`
`GOOGLE_CLOUD_STORAGE_BUCKET: {your_storage_bucket}`

**Already in my `config/filesystems.php` file I include:**
`'gcs' => [`
`'driver' => 'gcs',`
`'project_id' => env('GOOGLE_CLOUD_PROJECT_ID', '{include_project_id}'),`
`'key_file' => env('GOOGLE_CLOUD_KEY_FILE', base_path()."\key.json"),`
`'bucket' => env('GOOGLE_CLOUD_STORAGE_BUCKET', '{your_storage_bucket}'),`
`'path_prefix' => env('GOOGLE_CLOUD_STORAGE_PATH_PREFIX', null), // optional: /default/path/to/apply/in/bucket`
`'storage_api_uri' => env('GOOGLE_CLOUD_STORAGE_API_URI', null), // see: Public URLs below`

That was the way it worked for me, if you don't understand something let me know, my English is not very good.

**Comment by the-provost** [comment]
@victoralbino It might be a silly question but which folder do I have to paste the key.json into?

**Comment by victoralbino** [comment]
@the-provost in my case I left it at the ./ of the application along with .env, but you can put it in any folder of the application just by changing this line in the file **config/filesystems.php**

`'key_file' => env('GOOGLE_CLOUD_KEY_FILE', base_path()."\key.json"),`

**Comment by the-provost** [comment]
Is it safe to leave the key.json file in the project though?

**Comment by victoralbino** [comment]
When deploying the application you cannot leave the root of the application visible or publish, only the public folder, in which case it is safe, now if you leave the folder where the visible key file is located it is not safe
