### ISSUE TITLE
which function is best for writing to file

### ISSUE THREAD

**Issue by bere6255** [Superbalist/laravel-google-cloud-storage#65]
The stream or file "https://storage.googleapis.com/log/app_log-2019-06-28.log" could not be opened: failed to open stream: HTTP wrapper does not support writeable connections

**Comment by cjcox17** [comment]
Can you post a full stack trace and a code example? It's impossible to tell how or why you're getting that error without more information.

**Comment by bere6255** [comment]
(1/1) UnexpectedValueExceptionThe stream or file "https://storage.googleapis.com/sharphire-244918.appspot.com/log/app_log-2019-06-28.log" could not be opened: failed to open stream: HTTP wrapper does not support writeable connections
--
in StreamHandler.php line 107
at StreamHandler->write(array('message' => 'The stream or file "https://storage.googleapis.com/sharphire-244918.appspot.com/log/app_log-2019-06-28.log" could not be opened: failed to open stream: HTTP wrapper does not support writeable connections', 'context' => array('exception' =>object(UnexpectedValueException)), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'development', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-06-28 14:14:50] development.ERROR: The stream or file "https://storage.googleapis.com/sharphire-244918.appspot.com/log/app_log-2019-06-28.log" could not be opened: failed to open stream: HTTP wrapper does not support writeable connections {"exception":"[object] (UnexpectedValueException(code: 0): The stream or file \\"https://storage.googleapis.com/sharphire-244918.appspot.com/log/app_log-2019-06-28.log\\" could not be opened: failed to open stream: HTTP wrapper does not support writeable connections at /srv/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107)[stacktrace]#0 /srv/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\\\Handler\\\\StreamHandler->write(Array)#1 /srv/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\\\Handler\\\\RotatingFileHandler->write(Array)#2 /srv/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\\\Handler\\\\AbstractProcessingHandler->handle(Array)#3 /srv/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\\\Logger->addRecord(400, \'Class \'BeyondCo...\', Array)#4 /srv/vendor/laravel/framework/src/Illuminate/Log/Logger.php(176): Monolog\\\\Logger->error(\'Class \'BeyondCo...\', Array)#5 /srv/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\\\Log\\\\Logger->writeLog(\'error\', \'Class \'BeyondCo...\', Array)#6 /srv/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(500): Illuminate\\\\Log\\\\Logger->error(\'Class \'BeyondCo...\', Array)#7 /srv/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\\\Log\\\\LogManager->error(\'Class \'BeyondCo...\', Array)#8 /srv/app/Exceptions/Handler.php(37): Illuminate\\\\Foundation\\\\Exceptions\\\\Handler->report(Object(Symfony\\\\Component\\\\Debug\\\\Exception\\\\FatalThrowableError))#9 /srv/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\\\Exceptions\\\\Handler->report(Object(Symfony\\\\Component\\\\Debug\\\\Exception\\\\FatalThrowableError))#10 /srv/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\\\\Foundation\\\\Http\\\\Kernel->reportException(Object(Symfony\\\\Component\\\\Debug\\\\Exception\\\\FatalThrowableError))#11 /srv/public/index.php(55): Illuminate\\\\Foundation\\\\Http\\\\Kernel->handle(Object(Illuminate\\\\Http\\\\Request))#12 {main}"} '))

**Comment by bere6255** [comment]
this have been resolved
