### ISSUE TITLE
Chunk upload/ Resumable upload

### ISSUE THREAD

**Issue by ameerzulkarnain** [Superbalist/laravel-google-cloud-storage#72]
Hi. I was wondering does this package support chunk upload or can I make Google Cloud Storage API call using this package. API examples:

https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload

Thanks.

**Comment by flexgrip** [comment]
I wanted to know the same thing. So I grep'd this entire repo and the word resume doesn't exist. So what I did was just make the post request to google manually and got the resumable upload url.

Hope this helps. But I'm fairly sure this library does not externally support resumable chunk uploads. You'd have to upload to your laravel storage first, then stream the file into GCS using this packages copy/move methods.

**Comment by flexgrip** [comment]
Never mind. I may be wrong. Here's a code snippet that seems to work.

```
public static function getSignedGcsUrl($objPath, $duration = 50)
{
    return Storage::disk('gcs'/* following your filesystem configuration */)
        ->getAdapter()
        ->getBucket()
        ->object($objPath)
        ->signedUrl(new \DateTime('+ ' . $duration . ' seconds'));
}
```

I found it from this [stackoverflow post](https://stackoverflow.com/questions/20493080/how-to-generate-signed-url-for-google-cloud-storage-objects-using-php)

**Comment by nicja** [comment]
Thank you @flexgrip

**Comment by flexgrip** [comment]
One addendum. To get a signed **upload** url, you have to request a signed upload session from the driver. So the last line should not use the `->signedUrl()` method but something like this:

`->beginSignedUploadSession(['origin' => 'https://your-domain-for-cors', 'contentType' => 'video/mp4']);`
