### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by gsabater** [Superbalist/laravel-google-cloud-storage#75]
Updating the package fails with laravel 6 as this requires illuminate up to laravel 5.*

**Comment by litan1106** [comment]
#74 someone already sent in a pr. still waiting for it to merge

**Comment by Nks** [comment]
Any updates on it?

**Comment by maherelgamil** [comment]
6.0 and 6.1

**Comment by nicja** [comment]
This has been added in https://github.com/Superbalist/laravel-google-cloud-storage/releases/tag/2.2.2
