### ISSUE TITLE
Improve the docs on changing permissions/visibility of files

### ISSUE THREAD

**Issue by mgallegos** [Superbalist/laravel-google-cloud-storage#8]
The URL obtained by the method **getUrl** only works if the file is share publicly.

Is it possible to mark a file as public when uploading the file? or is there an alternative to access the file in some other way?

**Comment by mgallegos** [comment]
Found it!

$filesystem->setVisibility('secret.txt', 'public');

**Comment by zoidbergwill** [comment]
We should probably improve the docs

**Comment by regiszanandrea** [comment]
@zoidbergwill I think this #30 could help :)

**Comment by vinay-vissh** [comment]
Following code can '**upload the file** as well as **make it public**" in **single request** to Google Storage.

    // Visibility issue:
    // > \Superbalist\LaravelGoogleCloudStorage\GoogleCloudStorageServiceProvider, which is used for Google Storage,
    //     does not use the value of 'visibility' for the gs disk in config('filesystems')
    // > So, lets just pass this ignored config as 4th argument in Storage::putFileAs()
    //
    $options = [];

    $visibility = config('filesystems.disks.' . config('filesystems.default') . '.visibility');
    if( $visibility != null ){
        $options['visibility'] = $visibility;
    }

    /*$pathUploadedFile =*/ \Storage::putFileAs($location, $file, $fileName, $options);

Slightly bigger version of this reply can be found [here](https://github.com/Superbalist/laravel-google-cloud-storage/issues/22#issuecomment-380784611).

> Using v2.0.0 of this package.
