### ISSUE TITLE
fclose(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by tao** [Superbalist/laravel-google-cloud-storage#86]
I'm trying Google Storage on a new Laravel / Statamic project and I've run into this issue when uploading my files.

`fclose(): supplied resource is not a valid stream resource`

Is anyone familiar with this problem and is it related to this package? I'm having trouble finding the source of the issue...

**Comment by sergej-kurakin** [comment]
At which moment you get `fclose()` ? Is it resource you are uploading or it is happening from inside Google Cloud Storage code?

**Comment by tao** [comment]
Sorry, I did some more investigation to find out and found fclose() was in the Statamic code and I was able to resolve the issue with this fix. https://github.com/spatie/laravel-medialibrary/issues/698.
