### ISSUE TITLE
Disk [gcs] does not have a configured driver. Laravel 6.18.16

### ISSUE THREAD

**Issue by Davidsr** [Superbalist/laravel-google-cloud-storage#94]
Hi, anybody can help figure out what´s the problem?

**Disk [gcs] does not have a configured driver.**

My laravel version is 6.18.16 and Superbalist/laravel-google-cloud-storage 2.2

```
* @param  string  $name
     * @return \Illuminate\Contracts\Filesystem\Filesystem
     *
     * @throws \InvalidArgumentException
     */
    protected function resolve($name)
    {
        $config = $this->getConfig($name);
 
        if (empty($config['driver'])) {
            throw new InvalidArgumentException("Disk [{$name}] does not have a configured driver.");
        }
 
        $name = $config['driver'];
 
        if (isset($this->customCreators[$name])) {
            return $this->callCustomCreator($config);
        }
```
 

Thanks

**Comment by Davidsr** [comment]
This is my config/filesystem

`'gcs' => [
            'driver' => 'gcs',
            'project_id' => env('GOOGLE_CLOUD_PROJECT_ID', 'your-project-id'),
            'key_file' => env('GOOGLE_CLOUD_KEY_FILE', null), // optional: /path/to/service-account.json
            'bucket' => env('GOOGLE_CLOUD_STORAGE_BUCKET', 'your-bucket'),
            'path_prefix' => env('GOOGLE_CLOUD_STORAGE_PATH_PREFIX', null), // optional: /default/path/to/apply/in/bucket
            'storage_api_uri' => env('GOOGLE_CLOUD_STORAGE_API_URI', null), // see: Public URLs below
            'visibility' => 'public', // optional: public|private
        ],`

**Comment by SaidiAli** [comment]
@Davidsr the ‘gcs’ array has to belong in the disk array in the filesystems config file!

**Comment by Davidsr** [comment]
> @Davidsr the ‘gcs’ array has to belong in the disk array in the filesystems config file!

Yes @SaidiAli 
I revolved the problem with

`php artisan cache:clear`

Thanks
